name: Shell commands 

on: [push]

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    steps:
      - name: Lists Files 
        run: | 
          pwd
          ls -a
      - name: Checkout 
        uses: actions/checkout@v1

          
