name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    # Runs "at minute 50 past every hour" (see https://crontab.guru)
    - cron: '55 * * * *'
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: |
           echo "test"

          
