name: Shell commands 

on: [push]

job: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: multiline script 
        run: | 
          echo "hello"
          echo "test"
