name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    # Runs "at minute 50 past every hour" (see https://crontab.guru)
    - cron: '50 * * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
         run: echo 'test'

          
