name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    # Runs "at minute 50 past every hour" (see https://crontab.guru)
    - cron: '7 * * * *'
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
           npm -v
           pwd

          
